var words = 
[["grenadine","thin syrup made from pomegranate juice; used in mixed drinks","noun"],
["pomegranate","shrub or small tree having large red many-seeded fruit","noun"],
["hefty","of considerable weight and size","adjective"],
["gladiolus","any of numerous plants of the genus Gladiolus native chiefly to tropical and South Africa having sword-shaped leaves and one-sided spikes of brightly colored funnel-shaped flowers; widely cultivated","noun"],
["pelter","a thrower of missiles","noun"],
["concretize","make something concrete","verb"],
["manikin","a life-size dummy used to display clothes","noun"],
["canvass","get opinions by asking specific questions","noun or verb"],
["lubberly","clumsy and unskilled","adjective"],
["cordial","politely warm and friendly","adjective"],
["jocular","characterized by jokes and good humor","adjective"],
["Utopian","of or pertaining to or resembling a utopia","adjective"],
["tamp","press down tightly","verb"],
["subnormality","the state of being less than normal","adjective"],
["obbligato","a part of the score that must be performed without change or omission","noun"],
["woodsy","characteristic or suggestive of woods","adjective"],
["stevedore","a laborer who loads and unloads vessels in a port","noun"],
["effervescence","the process of bubbling as gas escapes","noun"],
["bromidic","given to uttering bromides","adjective"],
["canoodle","fondle or pet affectionately","verb"],
["satrap","a governor of a province in ancient Persia","noun"],
["congeries","a sum total of many heterogenous things taken together","noun"],
["twain","two items of the same kind","noun"],
["kittiwake","small pearl-grey gull of northern regions","noun"],
["polysemy","the ambiguity of an individual word or phrase that can be used (in different contexts) to express two or more different meanings","noun"],
["madrigal","an unaccompanied partsong for several voices","noun"],
["bollard","a strong post","noun"],
["parvenu","a person who has suddenly risen to a higher economic status","noun"],
["bowdlerize","edit by omitting or modifying parts considered indelicate","verb"],
["mountebank","a flamboyant deceiver","noun"],
["hauteur","overbearing pride with a superior manner toward inferiors","noun"],
["asphodel","any of various chiefly Mediterranean plants of the genera Asphodeline and Asphodelus having linear leaves and racemes of white or pink or yellow flowers","noun"],
["annulment","an official or legal cancellation","noun"],
["quasi","having some resemblance","adjective"],
["Yugoslavia","a former country of southeastern Europe bordering the Adriatic Sea; formed in 1918 and named Yugoslavia in 1929; controlled by Marshal Tito as a communist state until his death in 1980","noun"],
["paleobotany","the study of fossil plants","noun"],
["cephalopodan","relating or belonging to the class Cephalopoda","noun"],
["Serbian","of or relating to the people or language or culture of the region of Serbia","adjective"],
["tribunal","an assembly to conduct judicial business","noun"],
["ague","successive stages of chills and fever that is a symptom of malaria","noun"],
["Netherlands","a constitutional monarchy in western Europe on the North Sea","noun"],
["Bosnian","of or relating to or characteristic of Bosnia-Herzegovina or the people of Bosnia","adjective"],
["Albanian","of or relating to Albania or its people or language or culture","adjective"],
["Kosovo","a republic in the Balkan Peninsula that declared independence from Serbia in 2008; populated predominantly by Albanians","noun"],
["Chile","a republic in southern South America on the western slopes of the Andes on the south Pacific coast","noun"],
["humiliating","causing embarrassment or awareness of your shortcomings","adjective"],
["Suharto","Indonesian statesman who seized power from Sukarno in 1967","person"],
["contemplate","think intently and at length, as for spiritual purposes","verb"],
["Peruvian","of or relating to or characteristic of Peru or its people","adjective"],
["oust","remove from a position or office","verb"],
["Saddam Hussein","Iraqi leader who waged war against Iran","person"],
["subsequently","happening at a time later than another time","adjective"],
["massacre","the savage and excessive killing of many people","verb"],
["civilian","a nonmilitary citizen","adjective,noun"],
["revolt","rise up against an authority","verb,noun"],
["fascist","an adherent of right-wing authoritarian views","noun,adjective"],
["revered","profoundly honored","adjective"],
["regime","the governing authority of a political unit","noun"],
["Mandela","South African statesman who was released from prison to become the nation's first democratically elected president in 1994 (born in 1918)","noun,person"],
["triumphantly","in a triumphant manner","adjective"],
["Pretoria","city in the Transvaal","noun,place"],
["culminate","end, especially to reach a final or climactic stage","verb"],
["assassinated","murdered by surprise attack for political reasons","adjective"],
["Ferdinand I","king of Castile and Leon who achieved control of the Moorish kings of Saragossa and Seville and Toledo (1016-1065)","noun,person"],
["Suharto","Indonesian statesman who seized power from Sukarno in 1967","noun,person"],
["Burmese","of or relating to or characteristic of Myanmar or its people","adjective"],
["Beijing","capital of the People's Republic of China in the Hebei province in northeastern China; 2nd largest Chinese city","noun,place"],
["Kyrgyzstan","a landlocked republic in west central Asia bordering on northwestern China; formerly an Asian soviet but became independent in 1991","noun,place"],
["Venezuela","a republic in northern South America on the Caribbean","adjective"],
["charismatic","possessing an extraordinary ability to attract","adjective"],
["daw","common black-and-grey Eurasian bird noted for thievery","noun"],
["upsurge","a sudden or abrupt strong increase","noun"],
["suffrage","a legal right to vote","noun"],
["minimal","the least possible","adjective"],
["insurgency","an organized rebellion aimed at overthrowing a government","noun"],
["Sri Lanka","a republic on the island of Ceylon","noun,place"],
["torture","infliction of suffering to punish or obtain information","verb"],
["Guatemala","a republic in Central America","noun,place"],
["Bangladesh","a Muslim republic in southern Asia bordered by India to the north and west and east and the Bay of Bengal to the south; formerly part of India and then part of Pakistan; it achieved independence in 1971","noun,place"],
["manipulate","influence or control shrewdly or deviously","verb"],
["Bolivia","a landlocked republic in central South America","noun,place"],
["stringent","demanding strict attention to rules and procedures","adjective"],
["vulnerable","capable of being wounded or hurt","adjective"],
["prod","push against gently","verb"],
["famine","a severe shortage of food resulting in starvation and death","noun"],
["eradicate","destroy completely, as if down to the roots",""]
]